name: Auto Update TV360 Token

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: |
          sudo apt update
          sudo apt install -y jq

      - name: Get latest token
        run: |
          PAGE=$(curl -L -s "https://vpsttt.vietanhtv.top/tv/")

          TOKEN=$(echo "$PAGE" | grep -oP 'token=\K[a-zA-Z0-9]+' | head -1)

          echo "TOKEN=$TOKEN" >> $GITHUB_ENV

          echo "Found token: $TOKEN"

      - name: Replace token in M3U
        run: |
          find . -name "*.m3u" -type f | while read file; do
            sed -i "s|token=[a-zA-Z0-9]*|token=${TOKEN}|g" "$file"
          done

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add .

          git commit -m "Auto update TV360 token" || echo "No changes"

          git push
