name: Auto Merge EPG

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  merge-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y wget gzip

      - name: Download EPG files
        run: |
          mkdir -p epg

          wget -O epg/vnepg.xml.gz "https://vnepg.site/epg.xml.gz"
          wget -O epg/lichphatsong.xml.gz "https://lichphatsong.site/schedule/epg.xml.gz"

      - name: Extract EPG
        run: |
          gunzip -f epg/vnepg.xml.gz
          gunzip -f epg/lichphatsong.xml.gz

      - name: Merge EPG
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > epg.xml
          echo '<tv>' >> epg.xml

          sed '1,2d;$d' epg/vnepg.xml >> epg.xml
          sed '1,2d;$d' epg/lichphatsong.xml >> epg.xml

          echo '</tv>' >> epg.xml

      - name: Commit merged EPG
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add epg.xml
          git commit -m "Auto update merged EPG" || echo "No changes"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
